import 'dart:io';
import 'package:http/http.dart' as http;
import 'dart:convert';

class Flashcard {
  final String hanzi;
  final String pinyin;
  final String meaning;
  final String audioFilePath;

  Flashcard(
      {required this.hanzi,
      required this.pinyin,
      required this.meaning,
      required this.audioFilePath});
}

void main() async {
  var flashcards = [
    Flashcard(
      hanzi: '爱',
      pinyin: 'ài',
      meaning: 'amar',
      audioFilePath: 'sounds/爱.mp3',
    ),
    Flashcard(
      hanzi: '八',
      pinyin: 'bā',
      meaning: 'ocho',
      audioFilePath: 'sounds/八.mp3',
    ),
    Flashcard(
      hanzi: '爸爸',
      pinyin: 'bàba',
      meaning: 'padre',
      audioFilePath: 'sounds/爸爸.mp3',
    ),
    Flashcard(
      hanzi: '杯子',
      pinyin: 'bēizi',
      meaning: 'vaso, taza',
      audioFilePath: 'sounds/杯子.mp3',
    ),
    Flashcard(
      hanzi: '北京',
      pinyin: 'Běijīng',
      meaning: 'Pekín',
      audioFilePath: 'sounds/北京.mp3',
    ),
    Flashcard(
      hanzi: '本',
      pinyin: 'běn',
      meaning: 'clasificador para libros',
      audioFilePath: 'sounds/本.mp3',
    ),
    Flashcard(
      hanzi: '不',
      pinyin: 'bù',
      meaning: 'no',
      audioFilePath: 'sounds/不.mp3',
    ),
    Flashcard(
      hanzi: '菜',
      pinyin: 'cài',
      meaning: 'plato, comida, verdura',
      audioFilePath: 'sounds/菜.mp3',
    ),
    Flashcard(
      hanzi: '茶',
      pinyin: 'chá',
      meaning: 'té',
      audioFilePath: 'sounds/茶.mp3',
    ),
    Flashcard(
      hanzi: '吃',
      pinyin: 'chī',
      meaning: 'comer',
      audioFilePath: 'sounds/吃.mp3',
    ),
    Flashcard(
      hanzi: '出租车',
      pinyin: 'chūzūchē',
      meaning: 'taxi',
      audioFilePath: 'sounds/出租车.mp3',
    ),
    Flashcard(
      hanzi: '打电话',
      pinyin: 'dǎ diànhuà',
      meaning: 'llamar por teléfono',
      audioFilePath: 'sounds/打电话.mp3',
    ),
    Flashcard(
      hanzi: '大',
      pinyin: 'dà',
      meaning: 'grande',
      audioFilePath: 'sounds/大.mp3',
    ),
    Flashcard(
      hanzi: '的',
      pinyin: 'de',
      meaning: 'partícula posesiva',
      audioFilePath: 'sounds/的.mp3',
    ),
    Flashcard(
      hanzi: '点',
      pinyin: 'diǎn',
      meaning: 'hora',
      audioFilePath: 'sounds/点.mp3',
    ),
    Flashcard(
      hanzi: '电脑',
      pinyin: 'diànnǎo',
      meaning: 'ordenador',
      audioFilePath: 'sounds/电脑.mp3',
    ),
    Flashcard(
      hanzi: '电视',
      pinyin: 'diànshì',
      meaning: 'televisión',
      audioFilePath: 'sounds/电视.mp3',
    ),
    Flashcard(
      hanzi: '电影',
      pinyin: 'diànyǐng',
      meaning: 'película',
      audioFilePath: 'sounds/电影.mp3',
    ),
    Flashcard(
      hanzi: '东西',
      pinyin: 'dōngxi',
      meaning: 'cosa',
      audioFilePath: 'sounds/东西.mp3',
    ),
    Flashcard(
      hanzi: '都',
      pinyin: 'dōu',
      meaning: 'todos',
      audioFilePath: 'sounds/都.mp3',
    ),
    Flashcard(
      hanzi: '读',
      pinyin: 'dú',
      meaning: 'leer',
      audioFilePath: 'sounds/读.mp3',
    ),
    Flashcard(
      hanzi: '对不起',
      pinyin: 'duìbuqǐ',
      meaning: 'lo siento',
      audioFilePath: 'sounds/对不起.mp3',
    ),
    Flashcard(
      hanzi: '多',
      pinyin: 'duō',
      meaning: 'mucho',
      audioFilePath: 'sounds/多.mp3',
    ),
    Flashcard(
      hanzi: '多少',
      pinyin: 'duōshao',
      meaning: 'cuánto',
      audioFilePath: 'sounds/多少.mp3',
    ),
    Flashcard(
      hanzi: '儿子',
      pinyin: 'érzi',
      meaning: 'hijo',
      audioFilePath: 'sounds/儿子.mp3',
    ),
    Flashcard(
      hanzi: '二',
      pinyin: 'èr',
      meaning: 'dos',
      audioFilePath: 'sounds/二.mp3',
    ),
    Flashcard(
      hanzi: '饭馆',
      pinyin: 'fànguǎn',
      meaning: 'restaurante',
      audioFilePath: 'sounds/饭馆.mp3',
    ),
    Flashcard(
      hanzi: '飞机',
      pinyin: 'fēijī',
      meaning: 'avión',
      audioFilePath: 'sounds/飞机.mp3',
    ),
    Flashcard(
      hanzi: '分钟',
      pinyin: 'fēnzhōng',
      meaning: 'minuto',
      audioFilePath: 'sounds/分钟.mp3',
    ),
    Flashcard(
      hanzi: '高兴',
      pinyin: 'gāoxìng',
      meaning: 'feliz',
      audioFilePath: 'sounds/高兴.mp3',
    ),
    Flashcard(
      hanzi: '个',
      pinyin: 'gè',
      meaning: 'clasificador general',
      audioFilePath: 'sounds/个.mp3',
    ),
    Flashcard(
      hanzi: '工作',
      pinyin: 'gōngzuò',
      meaning: 'trabajo',
      audioFilePath: 'sounds/工作.mp3',
    ),
    Flashcard(
      hanzi: '狗',
      pinyin: 'gǒu',
      meaning: 'perro',
      audioFilePath: 'sounds/狗.mp3',
    ),
    Flashcard(
      hanzi: '汉语',
      pinyin: 'Hànyǔ',
      meaning: 'chino (idioma)',
      audioFilePath: 'sounds/汉语.mp3',
    ),
    Flashcard(
      hanzi: '好',
      pinyin: 'hǎo',
      meaning: 'bueno',
      audioFilePath: 'sounds/好.mp3',
    ),
    Flashcard(
      hanzi: '号',
      pinyin: 'hào',
      meaning: 'día (del mes)',
      audioFilePath: 'sounds/号.mp3',
    ),
    Flashcard(
      hanzi: '喝',
      pinyin: 'hē',
      meaning: 'beber',
      audioFilePath: 'sounds/喝.mp3',
    ),
    Flashcard(
      hanzi: '和',
      pinyin: 'hé',
      meaning: 'y',
      audioFilePath: 'sounds/和.mp3',
    ),
    Flashcard(
      hanzi: '很',
      pinyin: 'hěn',
      meaning: 'muy',
      audioFilePath: 'sounds/很.mp3',
    ),
    Flashcard(
      hanzi: '后面',
      pinyin: 'hòumiàn',
      meaning: 'detrás',
      audioFilePath: 'sounds/后面.mp3',
    ),
    Flashcard(
      hanzi: '回',
      pinyin: 'huí',
      meaning: 'volver',
      audioFilePath: 'sounds/回.mp3',
    ),
    Flashcard(
      hanzi: '会',
      pinyin: 'huì',
      meaning: 'saber (hacer algo)',
      audioFilePath: 'sounds/会.mp3',
    ),
    Flashcard(
      hanzi: '火车站',
      pinyin: 'huǒchēzhàn',
      meaning: 'estación de tren',
      audioFilePath: 'sounds/火车站.mp3',
    ),
    Flashcard(
      hanzi: '几',
      pinyin: 'jǐ',
      meaning: 'cuántos',
      audioFilePath: 'sounds/几.mp3',
    ),
    Flashcard(
      hanzi: '家',
      pinyin: 'jiā',
      meaning: 'casa',
      audioFilePath: 'sounds/家.mp3',
    ),
    Flashcard(
      hanzi: '叫',
      pinyin: 'jiào',
      meaning: 'llamarse',
      audioFilePath: 'sounds/叫.mp3',
    ),
    Flashcard(
      hanzi: '今天',
      pinyin: 'jīntiān',
      meaning: 'hoy',
      audioFilePath: 'sounds/今天.mp3',
    ),
    Flashcard(
      hanzi: '九',
      pinyin: 'jiǔ',
      meaning: 'nueve',
      audioFilePath: 'sounds/九.mp3',
    ),
    Flashcard(
      hanzi: '开',
      pinyin: 'kāi',
      meaning: 'abrir, conducir',
      audioFilePath: 'sounds/开.mp3',
    ),
    Flashcard(
      hanzi: '看',
      pinyin: 'kàn',
      meaning: 'ver, mirar',
      audioFilePath: 'sounds/看.mp3',
    ),
    Flashcard(
      hanzi: '看见',
      pinyin: 'kànjiàn',
      meaning: 'ver (alcanzar a ver)',
      audioFilePath: 'sounds/看见.mp3',
    ),
    Flashcard(
      hanzi: '块',
      pinyin: 'kuài',
      meaning: 'clasificador para dinero',
      audioFilePath: 'sounds/块.mp3',
    ),
    Flashcard(
      hanzi: '来',
      pinyin: 'lái',
      meaning: 'venir',
      audioFilePath: 'sounds/来.mp3',
    ),
    Flashcard(
      hanzi: '老师',
      pinyin: 'lǎoshī',
      meaning: 'maestro',
      audioFilePath: 'sounds/老师.mp3',
    ),
    Flashcard(
      hanzi: '了',
      pinyin: 'le',
      meaning: 'partícula de pasado',
      audioFilePath: 'sounds/了.mp3',
    ),
    Flashcard(
      hanzi: '冷',
      pinyin: 'lěng',
      meaning: 'frío',
      audioFilePath: 'sounds/冷.mp3',
    ),
    Flashcard(
      hanzi: '里',
      pinyin: 'lǐ',
      meaning: 'dentro',
      audioFilePath: 'sounds/里.mp3',
    ),
    Flashcard(
      hanzi: '六',
      pinyin: 'liù',
      meaning: 'seis',
      audioFilePath: 'sounds/六.mp3',
    ),
    Flashcard(
      hanzi: '妈妈',
      pinyin: 'māma',
      meaning: 'madre',
      audioFilePath: 'sounds/妈妈.mp3',
    ),
    Flashcard(
      hanzi: '吗',
      pinyin: 'ma',
      meaning: 'partícula interrogativa',
      audioFilePath: 'sounds/吗.mp3',
    ),
    Flashcard(
      hanzi: '买',
      pinyin: 'mǎi',
      meaning: 'comprar',
      audioFilePath: 'sounds/买.mp3',
    ),
    Flashcard(
      hanzi: '猫',
      pinyin: 'māo',
      meaning: 'gato',
      audioFilePath: 'sounds/猫.mp3',
    ),
    Flashcard(
      hanzi: '没',
      pinyin: 'méi',
      meaning: 'no tener',
      audioFilePath: 'sounds/没.mp3',
    ),
    Flashcard(
      hanzi: '没有',
      pinyin: 'méiyǒu',
      meaning: 'no tener',
      audioFilePath: 'sounds/没有.mp3',
    ),
    Flashcard(
      hanzi: '米饭',
      pinyin: 'mǐfàn',
      meaning: 'arroz cocido',
      audioFilePath: 'sounds/米饭.mp3',
    ),
    Flashcard(
      hanzi: '明天',
      pinyin: 'míngtiān',
      meaning: 'mañana',
      audioFilePath: 'sounds/明天.mp3',
    ),
    Flashcard(
      hanzi: '名字',
      pinyin: 'míngzi',
      meaning: 'nombre',
      audioFilePath: 'sounds/名字.mp3',
    ),
    Flashcard(
      hanzi: '哪',
      pinyin: 'nǎ',
      meaning: 'cuál',
      audioFilePath: 'sounds/哪.mp3',
    ),
    Flashcard(
      hanzi: '那',
      pinyin: 'nà',
      meaning: 'eso',
      audioFilePath: 'sounds/那.mp3',
    ),
    Flashcard(
      hanzi: '呢',
      pinyin: 'ne',
      meaning: 'partícula interrogativa',
      audioFilePath: 'sounds/呢.mp3',
    ),
    Flashcard(
      hanzi: '能',
      pinyin: 'néng',
      meaning: 'poder',
      audioFilePath: 'sounds/能.mp3',
    ),
    Flashcard(
      hanzi: '你',
      pinyin: 'nǐ',
      meaning: 'tú',
      audioFilePath: 'sounds/你.mp3',
    ),
    Flashcard(
      hanzi: '年',
      pinyin: 'nián',
      meaning: 'año',
      audioFilePath: 'sounds/年.mp3',
    ),
    Flashcard(
      hanzi: '女儿',
      pinyin: 'nǚ´ér',
      meaning: 'hija',
      audioFilePath: 'sounds/女儿.mp3',
    ),
    Flashcard(
      hanzi: '朋友',
      pinyin: 'péngyou',
      meaning: 'amigo',
      audioFilePath: 'sounds/朋友.mp3',
    ),
    Flashcard(
      hanzi: '漂亮',
      pinyin: 'piàoliang',
      meaning: 'bonita',
      audioFilePath: 'sounds/漂亮.mp3',
    ),
    Flashcard(
      hanzi: '苹果',
      pinyin: 'píngguǒ',
      meaning: 'manzana',
      audioFilePath: 'sounds/苹果.mp3',
    ),
    Flashcard(
      hanzi: '七',
      pinyin: 'qī',
      meaning: 'siete',
      audioFilePath: 'sounds/七.mp3',
    ),
    Flashcard(
      hanzi: '钱',
      pinyin: 'qián',
      meaning: 'dinero',
      audioFilePath: 'sounds/钱.mp3',
    ),
    Flashcard(
      hanzi: '前面',
      pinyin: 'qiánmiàn',
      meaning: 'delante',
      audioFilePath: 'sounds/前面.mp3',
    ),
    Flashcard(
      hanzi: '请',
      pinyin: 'qǐng',
      meaning: 'por favor',
      audioFilePath: 'sounds/请.mp3',
    ),
    Flashcard(
      hanzi: '去',
      pinyin: 'qù',
      meaning: 'ir',
      audioFilePath: 'sounds/去.mp3',
    ),
    Flashcard(
      hanzi: '热',
      pinyin: 'rè',
      meaning: 'calor',
      audioFilePath: 'sounds/热.mp3',
    ),
    Flashcard(
      hanzi: '人',
      pinyin: 'rén',
      meaning: 'persona',
      audioFilePath: 'sounds/人.mp3',
    ),
    Flashcard(
      hanzi: '认识',
      pinyin: 'rènshi',
      meaning: 'conocer',
      audioFilePath: 'sounds/认识.mp3',
    ),
    Flashcard(
      hanzi: '三',
      pinyin: 'sān',
      meaning: 'tres',
      audioFilePath: 'sounds/三.mp3',
    ),
    Flashcard(
      hanzi: '商店',
      pinyin: 'shāngdiàn',
      meaning: 'tienda',
      audioFilePath: 'sounds/商店.mp3',
    ),
    Flashcard(
      hanzi: '上',
      pinyin: 'shàng',
      meaning: 'encima',
      audioFilePath: 'sounds/上.mp3',
    ),
    Flashcard(
      hanzi: '上午',
      pinyin: 'shàngwǔ',
      meaning: 'mañana',
      audioFilePath: 'sounds/上午.mp3',
    ),
    Flashcard(
      hanzi: '少',
      pinyin: 'shǎo',
      meaning: 'poco',
      audioFilePath: 'sounds/少.mp3',
    ),
    Flashcard(
      hanzi: '谁',
      pinyin: 'shéi',
      meaning: 'quién',
      audioFilePath: 'sounds/谁.mp3',
    ),
    Flashcard(
      hanzi: '什么',
      pinyin: 'shénme',
      meaning: 'qué',
      audioFilePath: 'sounds/什么.mp3',
    ),
    Flashcard(
      hanzi: '十',
      pinyin: 'shí',
      meaning: 'diez',
      audioFilePath: 'sounds/十.mp3',
    ),
    Flashcard(
      hanzi: '时候',
      pinyin: 'shíhou',
      meaning: 'tiempo, momento',
      audioFilePath: 'sounds/时候.mp3',
    ),
    Flashcard(
      hanzi: '是',
      pinyin: 'shì',
      meaning: 'ser',
      audioFilePath: 'sounds/是.mp3',
    ),
    Flashcard(
      hanzi: '书',
      pinyin: 'shū',
      meaning: 'libro',
      audioFilePath: 'sounds/书.mp3',
    ),
    Flashcard(
      hanzi: '水',
      pinyin: 'shuǐ',
      meaning: 'agua',
      audioFilePath: 'sounds/水.mp3',
    ),
    Flashcard(
      hanzi: '水果',
      pinyin: 'shuǐguǒ',
      meaning: 'fruta',
      audioFilePath: 'sounds/水果.mp3',
    ),
    Flashcard(
      hanzi: '睡觉',
      pinyin: 'shuìjiào',
      meaning: 'dormir',
      audioFilePath: 'sounds/睡觉.mp3',
    ),
    Flashcard(
      hanzi: '说',
      pinyin: 'shuō',
      meaning: 'decir',
      audioFilePath: 'sounds/说.mp3',
    ),
    Flashcard(
      hanzi: '四',
      pinyin: 'sì',
      meaning: 'cuatro',
      audioFilePath: 'sounds/四.mp3',
    ),
    Flashcard(
      hanzi: '岁',
      pinyin: 'suì',
      meaning: 'año (de edad)',
      audioFilePath: 'sounds/岁.mp3',
    ),
    Flashcard(
      hanzi: '他',
      pinyin: 'tā',
      meaning: 'él',
      audioFilePath: 'sounds/他.mp3',
    ),
    Flashcard(
      hanzi: '她',
      pinyin: 'tā',
      meaning: 'ella',
      audioFilePath: 'sounds/她.mp3',
    ),
    Flashcard(
      hanzi: '太',
      pinyin: 'tài',
      meaning: 'demasiado',
      audioFilePath: 'sounds/太.mp3',
    ),
    Flashcard(
      hanzi: '天气',
      pinyin: 'tiānqì',
      meaning: 'clima',
      audioFilePath: 'sounds/天气.mp3',
    ),
    Flashcard(
      hanzi: '听',
      pinyin: 'tīng',
      meaning: 'escuchar',
      audioFilePath: 'sounds/听.mp3',
    ),
    Flashcard(
      hanzi: '同学',
      pinyin: 'tóngxué',
      meaning: 'compañero de clase',
      audioFilePath: 'sounds/同学.mp3',
    ),
    Flashcard(
      hanzi: '喂',
      pinyin: 'wèi',
      meaning: 'hola (por teléfono)',
      audioFilePath: 'sounds/喂.mp3',
    ),
    Flashcard(
      hanzi: '我',
      pinyin: 'wǒ',
      meaning: 'yo',
      audioFilePath: 'sounds/我.mp3',
    ),
    Flashcard(
      hanzi: '我们',
      pinyin: 'wǒmen',
      meaning: 'nosotros',
      audioFilePath: 'sounds/我们.mp3',
    ),
    Flashcard(
      hanzi: '五',
      pinyin: 'wǔ',
      meaning: 'cinco',
      audioFilePath: 'sounds/五.mp3',
    ),
    Flashcard(
      hanzi: '喜欢',
      pinyin: 'xǐhuan',
      meaning: 'gustar',
      audioFilePath: 'sounds/喜欢.mp3',
    ),
    Flashcard(
      hanzi: '下',
      pinyin: 'xià',
      meaning: 'debajo',
      audioFilePath: 'sounds/下.mp3',
    ),
    Flashcard(
      hanzi: '下午',
      pinyin: 'xiàwǔ',
      meaning: 'tarde (después del mediodía)',
      audioFilePath: 'sounds/下午.mp3',
    ),
    Flashcard(
      hanzi: '下雨',
      pinyin: 'xiàyǔ',
      meaning: 'llover',
      audioFilePath: 'sounds/下雨.mp3',
    ),
    Flashcard(
      hanzi: '先生',
      pinyin: 'xiānsheng',
      meaning: 'señor',
      audioFilePath: 'sounds/先生.mp3',
    ),
    Flashcard(
      hanzi: '现在',
      pinyin: 'xiànzài',
      meaning: 'ahora',
      audioFilePath: 'sounds/现在.mp3',
    ),
    Flashcard(
      hanzi: '想',
      pinyin: 'xiǎng',
      meaning: 'querer, pensar',
      audioFilePath: 'sounds/想.mp3',
    ),
    Flashcard(
      hanzi: '小',
      pinyin: 'xiǎo',
      meaning: 'pequeño',
      audioFilePath: 'sounds/小.mp3',
    ),
    Flashcard(
      hanzi: '小姐',
      pinyin: 'xiǎojie',
      meaning: 'señorita',
      audioFilePath: 'sounds/小姐.mp3',
    ),
    Flashcard(
      hanzi: '些',
      pinyin: 'xiē',
      meaning: 'algunos',
      audioFilePath: 'sounds/些.mp3',
    ),
    Flashcard(
      hanzi: '写',
      pinyin: 'xiě',
      meaning: 'escribir',
      audioFilePath: 'sounds/写.mp3',
    ),
    Flashcard(
      hanzi: '谢谢',
      pinyin: 'xièxie',
      meaning: 'gracias',
      audioFilePath: 'sounds/谢谢.mp3',
    ),
    Flashcard(
      hanzi: '星期',
      pinyin: 'xīngqī',
      meaning: 'semana',
      audioFilePath: 'sounds/星期.mp3',
    ),
    Flashcard(
      hanzi: '学生',
      pinyin: 'xuésheng',
      meaning: 'estudiante',
      audioFilePath: 'sounds/学生.mp3',
    ),
    Flashcard(
      hanzi: '学习',
      pinyin: 'xuéxí',
      meaning: 'estudiar',
      audioFilePath: 'sounds/学习.mp3',
    ),
    Flashcard(
      hanzi: '学校',
      pinyin: 'xuéxiào',
      meaning: 'escuela',
      audioFilePath: 'sounds/学校.mp3',
    ),
    Flashcard(
      hanzi: '一',
      pinyin: 'yī',
      meaning: 'uno',
      audioFilePath: 'sounds/一.mp3',
    ),
    Flashcard(
      hanzi: '衣服',
      pinyin: 'yīfu',
      meaning: 'ropa',
      audioFilePath: 'sounds/衣服.mp3',
    ),
    Flashcard(
      hanzi: '医生',
      pinyin: 'yīshēng',
      meaning: 'doctor',
      audioFilePath: 'sounds/医生.mp3',
    ),
    Flashcard(
      hanzi: '医院',
      pinyin: 'yīyuàn',
      meaning: 'hospital',
      audioFilePath: 'sounds/医院.mp3',
    ),
    Flashcard(
      hanzi: '椅子',
      pinyin: 'yǐzi',
      meaning: 'silla',
      audioFilePath: 'sounds/椅子.mp3',
    ),
    Flashcard(
      hanzi: '有',
      pinyin: 'yǒu',
      meaning: 'tener',
      audioFilePath: 'sounds/有.mp3',
    ),
    Flashcard(
      hanzi: '月',
      pinyin: 'yuè',
      meaning: 'mes',
      audioFilePath: 'sounds/月.mp3',
    ),
    Flashcard(
      hanzi: '在',
      pinyin: 'zài',
      meaning: 'en',
      audioFilePath: 'sounds/在.mp3',
    ),
    Flashcard(
      hanzi: '再见',
      pinyin: 'zàijiàn',
      meaning: 'adiós',
      audioFilePath: 'sounds/再见.mp3',
    ),
    Flashcard(
      hanzi: '怎么',
      pinyin: 'zěnme',
      meaning: 'cómo',
      audioFilePath: 'sounds/怎么.mp3',
    ),
    Flashcard(
      hanzi: '怎么样',
      pinyin: 'zěnmeyàng',
      meaning: 'qué tal',
      audioFilePath: 'sounds/怎么样.mp3',
    ),
    Flashcard(
      hanzi: '这',
      pinyin: 'zhè',
      meaning: 'esto',
      audioFilePath: 'sounds/这.mp3',
    ),
    Flashcard(
      hanzi: '中国',
      pinyin: 'Zhōngguó',
      meaning: 'China',
      audioFilePath: 'sounds/中国.mp3',
    ),
    Flashcard(
      hanzi: '中午',
      pinyin: 'zhōngwǔ',
      meaning: 'mediodía',
      audioFilePath: 'sounds/中午.mp3',
    ),
    Flashcard(
      hanzi: '住',
      pinyin: 'zhù',
      meaning: 'vivir',
      audioFilePath: 'sounds/住.mp3',
    ),
    Flashcard(
      hanzi: '桌子',
      pinyin: 'zhuōzi',
      meaning: 'mesa',
      audioFilePath: 'sounds/桌子.mp3',
    ),
    Flashcard(
      hanzi: '字',
      pinyin: 'zì',
      meaning: 'carácter',
      audioFilePath: 'sounds/字.mp3',
    ),
    Flashcard(
      hanzi: '昨天',
      pinyin: 'zuótiān',
      meaning: 'ayer',
      audioFilePath: 'sounds/昨天.mp3',
    ),
    Flashcard(
      hanzi: '做',
      pinyin: 'zuò',
      meaning: 'hacer',
      audioFilePath: 'sounds/做.mp3',
    ),
    Flashcard(
      hanzi: '坐',
      pinyin: 'zuò',
      meaning: 'sentarse',
      audioFilePath: 'sounds/坐.mp3',
    ),
    Flashcard(
      hanzi: '作',
      pinyin: 'zuò',
      meaning: 'trabajo, tarea',
      audioFilePath: 'sounds/作.mp3',
    ),
    Flashcard(
      hanzi: '作业',
      pinyin: 'zuòyè',
      meaning: 'tarea',
      audioFilePath: 'sounds/作业.mp3',
    ),
    Flashcard(
      hanzi: '昨天',
      pinyin: 'zuótiān',
      meaning: 'ayer',
      audioFilePath: 'sounds/昨天.mp3',
    ),
    Flashcard(
      hanzi: '走',
      pinyin: 'zǒu',
      meaning: 'caminar',
      audioFilePath: 'sounds/走.mp3',
    ),
    Flashcard(
      hanzi: '朋友',
      pinyin: 'péngyǒu',
      meaning: 'amigo',
      audioFilePath: 'sounds/朋友.mp3',
    ),
    Flashcard(
      hanzi: '说',
      pinyin: 'shuō',
      meaning: 'decir',
      audioFilePath: 'sounds/说.mp3',
    ),
    Flashcard(
      hanzi: '写',
      pinyin: 'xiě',
      meaning: 'escribir',
      audioFilePath: 'sounds/写.mp3',
    ),
    Flashcard(
      hanzi: '买',
      pinyin: 'mǎi',
      meaning: 'comprar',
      audioFilePath: 'sounds/买.mp3',
    ),
    Flashcard(
      hanzi: '家',
      pinyin: 'jiā',
      meaning: 'casa',
      audioFilePath: 'sounds/家.mp3',
    ),
    Flashcard(
      hanzi: '菜',
      pinyin: 'cài',
      meaning: 'comida',
      audioFilePath: 'sounds/菜.mp3',
    ),
    Flashcard(
      hanzi: '再',
      pinyin: 'zài',
      meaning: 'otra vez',
      audioFilePath: 'sounds/再.mp3',
    ),
    Flashcard(
      hanzi: '错',
      pinyin: 'cuò',
      meaning: 'error',
      audioFilePath: 'sounds/错.mp3',
    ),
    Flashcard(
      hanzi: '比',
      pinyin: 'bǐ',
      meaning: 'comparar',
      audioFilePath: 'sounds/比.mp3',
    ),
    Flashcard(
      hanzi: '票',
      pinyin: 'piào',
      meaning: 'billete',
      audioFilePath: 'sounds/票.mp3',
    ),
    Flashcard(
      hanzi: '课',
      pinyin: 'kè',
      meaning: 'lección',
      audioFilePath: 'sounds/课.mp3',
    ),
    Flashcard(
      hanzi: '考',
      pinyin: 'kǎo',
      meaning: 'examinar',
      audioFilePath: 'sounds/考.mp3',
    ),
    Flashcard(
      hanzi: '问',
      pinyin: 'wèn',
      meaning: 'preguntar',
      audioFilePath: 'sounds/问.mp3',
    ),
    Flashcard(
      hanzi: '懂',
      pinyin: 'dǒng',
      meaning: 'entender',
      audioFilePath: 'sounds/懂.mp3',
    ),
    Flashcard(
      hanzi: '帮',
      pinyin: 'bāng',
      meaning: 'ayudar',
      audioFilePath: 'sounds/帮.mp3',
    ),
    Flashcard(
      hanzi: '找',
      pinyin: 'zhǎo',
      meaning: 'buscar',
      audioFilePath: 'sounds/找.mp3',
    ),
    Flashcard(
      hanzi: '给',
      pinyin: 'gěi',
      meaning: 'dar',
      audioFilePath: 'sounds/给.mp3',
    ),
    Flashcard(
      hanzi: '进',
      pinyin: 'jìn',
      meaning: 'entrar',
      audioFilePath: 'sounds/进.mp3',
    ),
    Flashcard(
      hanzi: '等',
      pinyin: 'děng',
      meaning: 'esperar',
      audioFilePath: 'sounds/等.mp3',
    ),
    Flashcard(
      hanzi: '换',
      pinyin: 'huàn',
      meaning: 'cambiar',
      audioFilePath: 'sounds/换.mp3',
    ),
    Flashcard(
      hanzi: '穿',
      pinyin: 'chuān',
      meaning: 'vestir',
      audioFilePath: 'sounds/穿.mp3',
    ),
    Flashcard(
      hanzi: '送',
      pinyin: 'sòng',
      meaning: 'enviar',
      audioFilePath: 'sounds/送.mp3',
    ),
    Flashcard(
      hanzi: '到',
      pinyin: 'dào',
      meaning: 'llegar',
      audioFilePath: 'sounds/到.mp3',
    ),
    Flashcard(
      hanzi: '路',
      pinyin: 'lù',
      meaning: 'camino',
      audioFilePath: 'sounds/路.mp3',
    ),
    Flashcard(
      hanzi: '票',
      pinyin: 'piào',
      meaning: 'billete',
      audioFilePath: 'sounds/票.mp3',
    ),
    Flashcard(
      hanzi: '完',
      pinyin: 'wán',
      meaning: 'terminar',
      audioFilePath: 'sounds/完.mp3',
    ),
    Flashcard(
      hanzi: '准备',
      pinyin: 'zhǔnbèi',
      meaning: 'preparar',
      audioFilePath: 'sounds/准备.mp3',
    ),
    Flashcard(
      hanzi: '试',
      pinyin: 'shì',
      meaning: 'probar',
      audioFilePath: 'sounds/试.mp3',
    ),
    Flashcard(
      hanzi: '慢',
      pinyin: 'màn',
      meaning: 'lento',
      audioFilePath: 'sounds/慢.mp3',
    ),
    Flashcard(
      hanzi: '快',
      pinyin: 'kuài',
      meaning: 'rápido',
      audioFilePath: 'sounds/快.mp3',
    ),
    Flashcard(
      hanzi: '远',
      pinyin: 'yuǎn',
      meaning: 'lejos',
      audioFilePath: 'sounds/远.mp3',
    ),
    Flashcard(
      hanzi: '带',
      pinyin: 'dài',
      meaning: 'llevar',
      audioFilePath: 'sounds/带.mp3',
    ),
    Flashcard(
      hanzi: '起',
      pinyin: 'qǐ',
      meaning: 'levantarse',
      audioFilePath: 'sounds/起.mp3',
    ),
    Flashcard(
      hanzi: '车',
      pinyin: 'chē',
      meaning: 'coche',
      audioFilePath: 'sounds/车.mp3',
    ),
    Flashcard(
      hanzi: '张',
      pinyin: 'zhāng',
      meaning: 'abrir',
      audioFilePath: 'sounds/张.mp3',
    ),
    Flashcard(
      hanzi: '愿意',
      pinyin: 'yuànyì',
      meaning: 'desear',
      audioFilePath: 'sounds/愿意.mp3',
    ),
    Flashcard(
      hanzi: '需要',
      pinyin: 'xūyào',
      meaning: 'necesitar',
      audioFilePath: 'sounds/需要.mp3',
    ),
    Flashcard(
      hanzi: '帮助',
      pinyin: 'bāngzhù',
      meaning: 'ayuda',
      audioFilePath: 'sounds/帮助.mp3',
    ),
    Flashcard(
      hanzi: '会议',
      pinyin: 'huìyì',
      meaning: 'reunión',
      audioFilePath: 'sounds/会议.mp3',
    ),
    Flashcard(
      hanzi: '礼物',
      pinyin: 'lǐwù',
      meaning: 'regalo',
      audioFilePath: 'sounds/礼物.mp3',
    ),
    Flashcard(
      hanzi: '机场',
      pinyin: 'jīchǎng',
      meaning: 'aeropuerto',
      audioFilePath: 'sounds/机场.mp3',
    ),
    Flashcard(
      hanzi: '小心',
      pinyin: 'xiǎoxīn',
      meaning: 'tener cuidado',
      audioFilePath: 'sounds/小心.mp3',
    ),
    Flashcard(
      hanzi: '超市',
      pinyin: 'chāoshì',
      meaning: 'supermercado',
      audioFilePath: 'sounds/超市.mp3',
    ),
    Flashcard(
      hanzi: '总是',
      pinyin: 'zǒngshì',
      meaning: 'siempre',
      audioFilePath: 'sounds/总是.mp3',
    ),
    Flashcard(
      hanzi: '努力',
      pinyin: 'nǔlì',
      meaning: 'esforzarse',
      audioFilePath: 'sounds/努力.mp3',
    ),
    Flashcard(
      hanzi: '声音',
      pinyin: 'shēngyīn',
      meaning: 'sonido',
      audioFilePath: 'sounds/声音.mp3',
    ),
    Flashcard(
      hanzi: '新鲜',
      pinyin: 'xīnxiān',
      meaning: 'fresco',
      audioFilePath: 'sounds/新鲜.mp3',
    ),
    Flashcard(
      hanzi: '裤子',
      pinyin: 'kùzi',
      meaning: 'pantalones',
      audioFilePath: 'sounds/裤子.mp3',
    ),
    Flashcard(
      hanzi: '裙子',
      pinyin: 'qúnzi',
      meaning: 'falda',
      audioFilePath: 'sounds/裙子.mp3',
    ),
    Flashcard(
      hanzi: '方便',
      pinyin: 'fāngbiàn',
      meaning: 'conveniente',
      audioFilePath: 'sounds/方便.mp3',
    ),
    Flashcard(
      hanzi: '历史',
      pinyin: 'lìshǐ',
      meaning: 'historia',
      audioFilePath: 'sounds/历史.mp3',
    ),
    Flashcard(
      hanzi: '季节',
      pinyin: 'jìjié',
      meaning: 'estación',
      audioFilePath: 'sounds/季节.mp3',
    ),
    Flashcard(
      hanzi: '音乐',
      pinyin: 'yīnyuè',
      meaning: 'música',
      audioFilePath: 'sounds/音乐.mp3',
    ),
    Flashcard(
      hanzi: '健康',
      pinyin: 'jiànkāng',
      meaning: 'salud',
      audioFilePath: 'sounds/健康.mp3',
    ),
    Flashcard(
      hanzi: '数学',
      pinyin: 'shùxué',
      meaning: 'matemáticas',
      audioFilePath: 'sounds/数学.mp3',
    ),
    Flashcard(
      hanzi: '特别',
      pinyin: 'tèbié',
      meaning: 'especial',
      audioFilePath: 'sounds/特别.mp3',
    ),
    Flashcard(
      hanzi: '照顾',
      pinyin: 'zhàogu',
      meaning: 'cuidar',
      audioFilePath: 'sounds/照顾.mp3',
    ),
    Flashcard(
      hanzi: '复习',
      pinyin: 'fùxí',
      meaning: 'repasar',
      audioFilePath: 'sounds/复习.mp3',
    ),
    Flashcard(
      hanzi: '留学',
      pinyin: 'liúxué',
      meaning: 'estudiar en el extranjero',
      audioFilePath: 'sounds/留学.mp3',
    ),
    Flashcard(
      hanzi: '环境',
      pinyin: 'huánjìng',
      meaning: 'medio ambiente',
      audioFilePath: 'sounds/环境.mp3',
    ),
    Flashcard(
      hanzi: '机会',
      pinyin: 'jīhuì',
      meaning: 'oportunidad',
      audioFilePath: 'sounds/机会.mp3',
    ),
    Flashcard(
      hanzi: '爱情',
      pinyin: 'àiqíng',
      meaning: 'amor',
      audioFilePath: 'sounds/爱情.mp3',
    ),
    Flashcard(
      hanzi: '安排',
      pinyin: 'ānpái',
      meaning: 'organizar',
      audioFilePath: 'sounds/安排.mp3',
    ),
    Flashcard(
      hanzi: '安全',
      pinyin: 'ānquán',
      meaning: 'seguridad',
      audioFilePath: 'sounds/安全.mp3',
    ),
    Flashcard(
      hanzi: '抱歉',
      pinyin: 'bàoqiàn',
      meaning: 'disculpa',
      audioFilePath: 'sounds/抱歉.mp3',
    ),
    Flashcard(
      hanzi: '保护',
      pinyin: 'bǎohù',
      meaning: 'proteger',
      audioFilePath: 'sounds/保护.mp3',
    ),
    Flashcard(
      hanzi: '报名',
      pinyin: 'bàomíng',
      meaning: 'registrarse',
      audioFilePath: 'sounds/报名.mp3',
    ),
    Flashcard(
      hanzi: '不仅',
      pinyin: 'bùjǐn',
      meaning: 'no solo',
      audioFilePath: 'sounds/不仅.mp3',
    ),
    Flashcard(
      hanzi: '才',
      pinyin: 'cái',
      meaning: 'apenas',
      audioFilePath: 'sounds/才.mp3',
    ),
    Flashcard(
      hanzi: '材料',
      pinyin: 'cáiliào',
      meaning: 'material',
      audioFilePath: 'sounds/材料.mp3',
    ),
    Flashcard(
      hanzi: '成绩',
      pinyin: 'chéngjì',
      meaning: 'resultado',
      audioFilePath: 'sounds/成绩.mp3',
    ),
    Flashcard(
      hanzi: '出差',
      pinyin: 'chūchāi',
      meaning: 'viaje de negocios',
      audioFilePath: 'sounds/出差.mp3',
    ),
    Flashcard(
      hanzi: '打折',
      pinyin: 'dǎzhé',
      meaning: 'descuento',
      audioFilePath: 'sounds/打折.mp3',
    ),
    Flashcard(
      hanzi: '大约',
      pinyin: 'dàyuē',
      meaning: 'aproximadamente',
      audioFilePath: 'sounds/大约.mp3',
    ),
    Flashcard(
      hanzi: '代表',
      pinyin: 'dàibiǎo',
      meaning: 'representar',
      audioFilePath: 'sounds/代表.mp3',
    ),
    Flashcard(
      hanzi: '打算',
      pinyin: 'dǎsuàn',
      meaning: 'planear',
      audioFilePath: 'sounds/打算.mp3',
    ),
    Flashcard(
      hanzi: '发展',
      pinyin: 'fāzhǎn',
      meaning: 'desarrollar',
      audioFilePath: 'sounds/发展.mp3',
    ),
    Flashcard(
      hanzi: '方法',
      pinyin: 'fāngfǎ',
      meaning: 'método',
      audioFilePath: 'sounds/方法.mp3',
    ),
    Flashcard(
      hanzi: '房东',
      pinyin: 'fángdōng',
      meaning: 'casero',
      audioFilePath: 'sounds/房东.mp3',
    ),
    Flashcard(
      hanzi: '否则',
      pinyin: 'fǒuzé',
      meaning: 'de lo contrario',
      audioFilePath: 'sounds/否则.mp3',
    ),
    Flashcard(
      hanzi: '父母',
      pinyin: 'fùmǔ',
      meaning: 'padres',
      audioFilePath: 'sounds/父母.mp3',
    ),
    Flashcard(
      hanzi: '付款',
      pinyin: 'fùkuǎn',
      meaning: 'pagar',
      audioFilePath: 'sounds/付款.mp3',
    ),
    Flashcard(
      hanzi: '复印',
      pinyin: 'fùyìn',
      meaning: 'fotocopiar',
      audioFilePath: 'sounds/复印.mp3',
    ),
    Flashcard(
      hanzi: '广告',
      pinyin: 'guǎnggào',
      meaning: 'anuncio',
      audioFilePath: 'sounds/广告.mp3',
    ),
    Flashcard(
      hanzi: '过程',
      pinyin: 'guòchéng',
      meaning: 'proceso',
      audioFilePath: 'sounds/过程.mp3',
    ),
    Flashcard(
      hanzi: '护照',
      pinyin: 'hùzhào',
      meaning: 'pasaporte',
      audioFilePath: 'sounds/护照.mp3',
    ),
    Flashcard(
      hanzi: '回忆',
      pinyin: 'huíyì',
      meaning: 'recordar',
      audioFilePath: 'sounds/回忆.mp3',
    ),
    Flashcard(
      hanzi: '活动',
      pinyin: 'huódòng',
      meaning: 'actividad',
      audioFilePath: 'sounds/活动.mp3',
    ),
    Flashcard(
      hanzi: '获得',
      pinyin: 'huòdé',
      meaning: 'obtener',
      audioFilePath: 'sounds/获得.mp3',
    ),
    Flashcard(
      hanzi: '积累',
      pinyin: 'jīlěi',
      meaning: 'acumular',
      audioFilePath: 'sounds/积累.mp3',
    ),
    Flashcard(
      hanzi: '继续',
      pinyin: 'jìxù',
      meaning: 'continuar',
      audioFilePath: 'sounds/继续.mp3',
    ),
    Flashcard(
      hanzi: '爱护',
      pinyin: 'àihù',
      meaning: 'cuidar',
      audioFilePath: 'sounds/爱护.mp3',
    ),
    Flashcard(
      hanzi: '爱惜',
      pinyin: 'àixī',
      meaning: 'valorar',
      audioFilePath: 'sounds/爱惜.mp3',
    ),
    Flashcard(
      hanzi: '爱心',
      pinyin: 'àixīn',
      meaning: 'compasión',
      audioFilePath: 'sounds/爱心.mp3',
    ),
    Flashcard(
      hanzi: '安慰',
      pinyin: 'ānwèi',
      meaning: 'consolar',
      audioFilePath: 'sounds/安慰.mp3',
    ),
    Flashcard(
      hanzi: '安装',
      pinyin: 'ānzhuāng',
      meaning: 'instalar',
      audioFilePath: 'sounds/安装.mp3',
    ),
    Flashcard(
      hanzi: '熬夜',
      pinyin: 'áoyè',
      meaning: 'trasnochar',
      audioFilePath: 'sounds/熬夜.mp3',
    ),
    Flashcard(
      hanzi: '把握',
      pinyin: 'bǎwò',
      meaning: 'sujetar',
      audioFilePath: 'sounds/把握.mp3',
    ),
    Flashcard(
      hanzi: '摆',
      pinyin: 'bǎi',
      meaning: 'colocar',
      audioFilePath: 'sounds/摆.mp3',
    ),
    Flashcard(
      hanzi: '班主任',
      pinyin: 'bānzhǔrèn',
      meaning: 'tutor de clase',
      audioFilePath: 'sounds/班主任.mp3',
    ),
    Flashcard(
      hanzi: '办理',
      pinyin: 'bànlǐ',
      meaning: 'gestionar',
      audioFilePath: 'sounds/办理.mp3',
    ),
    Flashcard(
      hanzi: '傍晚',
      pinyin: 'bàngwǎn',
      meaning: 'atardecer',
      audioFilePath: 'sounds/傍晚.mp3',
    ),
    Flashcard(
      hanzi: '包裹',
      pinyin: 'bāoguǒ',
      meaning: 'paquete',
      audioFilePath: 'sounds/包裹.mp3',
    ),
    Flashcard(
      hanzi: '包子',
      pinyin: 'bāozi',
      meaning: 'bollo relleno',
      audioFilePath: 'sounds/包子.mp3',
    ),
    Flashcard(
      hanzi: '宝贝',
      pinyin: 'bǎobèi',
      meaning: 'tesoro',
      audioFilePath: 'sounds/宝贝.mp3',
    ),
    Flashcard(
      hanzi: '保持',
      pinyin: 'bǎochí',
      meaning: 'mantener',
      audioFilePath: 'sounds/保持.mp3',
    ),
    Flashcard(
      hanzi: '保存',
      pinyin: 'bǎocún',
      meaning: 'conservar',
      audioFilePath: 'sounds/保存.mp3',
    ),
    Flashcard(
      hanzi: '报到',
      pinyin: 'bàodào',
      meaning: 'registrarse',
      audioFilePath: 'sounds/报到.mp3',
    ),
    Flashcard(
      hanzi: '报道',
      pinyin: 'bàodào',
      meaning: 'reportar',
      audioFilePath: 'sounds/报道.mp3',
    ),
    Flashcard(
      hanzi: '报社',
      pinyin: 'bàoshè',
      meaning: 'oficina de periódico',
      audioFilePath: 'sounds/报社.mp3',
    ),
    Flashcard(
      hanzi: '抱怨',
      pinyin: 'bàoyuàn',
      meaning: 'quejarse',
      audioFilePath: 'sounds/抱怨.mp3',
    ),
    Flashcard(
      hanzi: '背',
      pinyin: 'bēi',
      meaning: 'llevar a la espalda',
      audioFilePath: 'sounds/背.mp3',
    ),
    Flashcard(
      hanzi: '背',
      pinyin: 'bèi',
      meaning: 'espalda',
      audioFilePath: 'sounds/背.mp3',
    ),
    Flashcard(
      hanzi: '背景',
      pinyin: 'bèijǐng',
      meaning: 'fondo',
      audioFilePath: 'sounds/背景.mp3',
    ),
    Flashcard(
      hanzi: '被子',
      pinyin: 'bèizi',
      meaning: 'manta',
      audioFilePath: 'sounds/被子.mp3',
    ),
    Flashcard(
      hanzi: '本科',
      pinyin: 'běnkē',
      meaning: 'licenciatura',
      audioFilePath: 'sounds/本科.mp3',
    ),
    Flashcard(
      hanzi: '本领',
      pinyin: 'běnlǐng',
      meaning: 'habilidad',
      audioFilePath: 'sounds/本领.mp3',
    ),
    Flashcard(
      hanzi: '本质',
      pinyin: 'běnzhì',
      meaning: 'esencia',
      audioFilePath: 'sounds/本质.mp3',
    ),
    Flashcard(
      hanzi: '彼此',
      pinyin: 'bǐcǐ',
      meaning: 'mutuamente',
      audioFilePath: 'sounds/彼此.mp3',
    ),
    Flashcard(
      hanzi: '比例',
      pinyin: 'bǐlì',
      meaning: 'proporción',
      audioFilePath: 'sounds/比例.mp3',
    ),
    Flashcard(
      hanzi: '必然',
      pinyin: 'bìrán',
      meaning: 'inevitable',
      audioFilePath: 'sounds/必然.mp3',
    ),
    Flashcard(
      hanzi: '爱不释手',
      pinyin: 'àibùshìshǒu',
      meaning: 'encantar',
      audioFilePath: 'sounds/爱不释手.mp3',
    ),
    Flashcard(
      hanzi: '爱戴',
      pinyin: 'àidài',
      meaning: 'apreciar',
      audioFilePath: 'sounds/爱戴.mp3',
    ),
    Flashcard(
      hanzi: '安居乐业',
      pinyin: 'ānjūlèyè',
      meaning: 'vivir y trabajar felizmente',
      audioFilePath: 'sounds/安居乐业.mp3',
    ),
    Flashcard(
      hanzi: '安宁',
      pinyin: 'ānníng',
      meaning: 'tranquilidad',
      audioFilePath: 'sounds/安宁.mp3',
    ),
    Flashcard(
      hanzi: '安详',
      pinyin: 'ānxiáng',
      meaning: 'sereno',
      audioFilePath: 'sounds/安详.mp3',
    ),
    Flashcard(
      hanzi: '安置',
      pinyin: 'ānzhì',
      meaning: 'colocar',
      audioFilePath: 'sounds/安置.mp3',
    ),
    Flashcard(
      hanzi: '昂贵',
      pinyin: 'ángguì',
      meaning: 'caro',
      audioFilePath: 'sounds/昂贵.mp3',
    ),
    Flashcard(
      hanzi: '熬',
      pinyin: 'áo',
      meaning: 'soportar',
      audioFilePath: 'sounds/熬.mp3',
    ),
    Flashcard(
      hanzi: '奥秘',
      pinyin: 'àomì',
      meaning: 'misterio',
      audioFilePath: 'sounds/奥秘.mp3',
    ),
    Flashcard(
      hanzi: '巴不得',
      pinyin: 'bābùdé',
      meaning: 'anhelar',
      audioFilePath: 'sounds/巴不得.mp3',
    ),
    Flashcard(
      hanzi: '巴结',
      pinyin: 'bājie',
      meaning: 'halagar',
      audioFilePath: 'sounds/巴结.mp3',
    ),
    Flashcard(
      hanzi: '拔苗助长',
      pinyin: 'bámiáozhùzhǎng',
      meaning: 'precipitarse',
      audioFilePath: 'sounds/拔苗助长.mp3',
    ),
    Flashcard(
      hanzi: '把关',
      pinyin: 'bǎguān',
      meaning: 'controlar',
      audioFilePath: 'sounds/把关.mp3',
    ),
    Flashcard(
      hanzi: '把手',
      pinyin: 'bǎshou',
      meaning: 'manija',
      audioFilePath: 'sounds/把手.mp3',
    ),
    Flashcard(
      hanzi: '罢工',
      pinyin: 'bàgōng',
      meaning: 'huelga',
      audioFilePath: 'sounds/罢工.mp3',
    ),
    Flashcard(
      hanzi: '霸道',
      pinyin: 'bàdào',
      meaning: 'arrogante',
      audioFilePath: 'sounds/霸道.mp3',
    ),
    Flashcard(
      hanzi: '摆脱',
      pinyin: 'bǎituō',
      meaning: 'deshacerse de',
      audioFilePath: 'sounds/摆脱.mp3',
    ),
    Flashcard(
      hanzi: '拜访',
      pinyin: 'bàifǎng',
      meaning: 'visitar',
      audioFilePath: 'sounds/拜访.mp3',
    ),
    Flashcard(
      hanzi: '拜年',
      pinyin: 'bàinián',
      meaning: 'felicitar el año nuevo',
      audioFilePath: 'sounds/拜年.mp3',
    ),
    Flashcard(
      hanzi: '拜托',
      pinyin: 'bàituō',
      meaning: 'encargar',
      audioFilePath: 'sounds/拜托.mp3',
    ),
    Flashcard(
      hanzi: '颁布',
      pinyin: 'bānbù',
      meaning: 'promulgar',
      audioFilePath: 'sounds/颁布.mp3',
    ),
    Flashcard(
      hanzi: '颁发',
      pinyin: 'bānfā',
      meaning: 'otorgar',
      audioFilePath: 'sounds/颁发.mp3',
    ),
    Flashcard(
      hanzi: '伴侣',
      pinyin: 'bànlǚ',
      meaning: 'compañero',
      audioFilePath: 'sounds/伴侣.mp3',
    ),
    Flashcard(
      hanzi: '伴随',
      pinyin: 'bànsuí',
      meaning: 'acompañar',
      audioFilePath: 'sounds/伴随.mp3',
    ),
    Flashcard(
      hanzi: '半途而废',
      pinyin: 'bàntúérfèi',
      meaning: 'abandonar a mitad de camino',
      audioFilePath: 'sounds/半途而废.mp3',
    ),
    Flashcard(
      hanzi: '扮演',
      pinyin: 'bànyǎn',
      meaning: 'representar',
      audioFilePath: 'sounds/扮演.mp3',
    ),
    Flashcard(
      hanzi: '绑架',
      pinyin: 'bǎngjià',
      meaning: 'secuestrar',
      audioFilePath: 'sounds/绑架.mp3',
    ),
    Flashcard(
      hanzi: '榜样',
      pinyin: 'bǎngyàng',
      meaning: 'modelo',
      audioFilePath: 'sounds/榜样.mp3',
    ),
    Flashcard(
      hanzi: '磅',
      pinyin: 'bàng',
      meaning: 'libra',
      audioFilePath: 'sounds/磅.mp3',
    ),
    Flashcard(
      hanzi: '包庇',
      pinyin: 'bāobì',
      meaning: 'encubrir',
      audioFilePath: 'sounds/包庇.mp3',
    ),
    Flashcard(
      hanzi: '爱戴',
      pinyin: 'àidài',
      meaning: 'querer y respetar',
      audioFilePath: 'sounds/爱戴.mp3',
    ),
    Flashcard(
      hanzi: '安宁',
      pinyin: 'ānníng',
      meaning: 'paz y tranquilidad',
      audioFilePath: 'sounds/安宁.mp3',
    ),
    Flashcard(
      hanzi: '安详',
      pinyin: 'ānxiáng',
      meaning: 'tranquilo y sereno',
      audioFilePath: 'sounds/安详.mp3',
    ),
    Flashcard(
      hanzi: '安置',
      pinyin: 'ānzhì',
      meaning: 'colocar; organizar',
      audioFilePath: 'sounds/安置.mp3',
    ),
    Flashcard(
      hanzi: '奥秘',
      pinyin: 'àomì',
      meaning: 'misterio',
      audioFilePath: 'sounds/奥秘.mp3',
    ),
    Flashcard(
      hanzi: '把关',
      pinyin: 'bǎguān',
      meaning: 'controlar',
      audioFilePath: 'sounds/把关.mp3',
    ),
    Flashcard(
      hanzi: '把手',
      pinyin: 'bǎshou',
      meaning: 'manija',
      audioFilePath: 'sounds/把手.mp3',
    ),
    Flashcard(
      hanzi: '罢工',
      pinyin: 'bàgōng',
      meaning: 'huelga',
      audioFilePath: 'sounds/罢工.mp3',
    ),
    Flashcard(
      hanzi: '摆脱',
      pinyin: 'bǎituō',
      meaning: 'deshacerse de',
      audioFilePath: 'sounds/摆脱.mp3',
    ),
    Flashcard(
      hanzi: '拜年',
      pinyin: 'bàinián',
      meaning: 'felicitar el año nuevo',
      audioFilePath: 'sounds/拜年.mp3',
    ),
    Flashcard(
      hanzi: '拜托',
      pinyin: 'bàituō',
      meaning: 'encargar',
      audioFilePath: 'sounds/拜托.mp3',
    ),
    Flashcard(
      hanzi: '颁布',
      pinyin: 'bānbù',
      meaning: 'promulgar',
      audioFilePath: 'sounds/颁布.mp3',
    ),
    Flashcard(
      hanzi: '颁发',
      pinyin: 'bānfā',
      meaning: 'otorgar',
      audioFilePath: 'sounds/颁发.mp3',
    ),
    Flashcard(
      hanzi: '伴侣',
      pinyin: 'bànlǚ',
      meaning: 'compañero',
      audioFilePath: 'sounds/伴侣.mp3',
    ),
    Flashcard(
      hanzi: '伴随',
      pinyin: 'bànsuí',
      meaning: 'acompañar',
      audioFilePath: 'sounds/伴随.mp3',
    ),
    Flashcard(
      hanzi: '半途而废',
      pinyin: 'bàntúérfèi',
      meaning: 'abandonar a mitad de camino',
      audioFilePath: 'sounds/半途而废.mp3',
    ),
    Flashcard(
      hanzi: '扮演',
      pinyin: 'bànyǎn',
      meaning: 'representar',
      audioFilePath: 'sounds/扮演.mp3',
    ),
    Flashcard(
      hanzi: '绑架',
      pinyin: 'bǎngjià',
      meaning: 'secuestrar',
      audioFilePath: 'sounds/绑架.mp3',
    ),
    Flashcard(
      hanzi: '榜样',
      pinyin: 'bǎngyàng',
      meaning: 'modelo',
      audioFilePath: 'sounds/榜样.mp3',
    ),
    Flashcard(
      hanzi: '磅',
      pinyin: 'bàng',
      meaning: 'libra',
      audioFilePath: 'sounds/磅.mp3',
    ),
    Flashcard(
      hanzi: '包庇',
      pinyin: 'bāobì',
      meaning: 'encubrir',
      audioFilePath: 'sounds/包庇.mp3',
    ),
    Flashcard(
      hanzi: '包袱',
      pinyin: 'bāofu',
      meaning: 'carga',
      audioFilePath: 'sounds/包袱.mp3',
    ),
    Flashcard(
      hanzi: '薄',
      pinyin: 'báo',
      meaning: 'delgado',
      audioFilePath: 'sounds/薄.mp3',
    ),
    Flashcard(
      hanzi: '保管',
      pinyin: 'bǎoguǎn',
      meaning: 'custodiar',
      audioFilePath: 'sounds/保管.mp3',
    ),
    Flashcard(
      hanzi: '保留',
      pinyin: 'bǎoliú',
      meaning: 'mantener',
      audioFilePath: 'sounds/保留.mp3',
    ),
    Flashcard(
      hanzi: '保密',
      pinyin: 'bǎomì',
      meaning: 'mantener en secreto',
      audioFilePath: 'sounds/保密.mp3',
    ),
    Flashcard(
      hanzi: '保姆',
      pinyin: 'bǎomǔ',
      meaning: 'niñera',
      audioFilePath: 'sounds/保姆.mp3',
    ),
    Flashcard(
      hanzi: '保守',
      pinyin: 'bǎoshǒu',
      meaning: 'conservador',
      audioFilePath: 'sounds/保守.mp3',
    ),
    Flashcard(
      hanzi: '保卫',
      pinyin: 'bǎowèi',
      meaning: 'defender',
      audioFilePath: 'sounds/保卫.mp3',
    ),
    Flashcard(
      hanzi: '保养',
      pinyin: 'bǎoyǎng',
      meaning: 'mantener',
      audioFilePath: 'sounds/保养.mp3',
    ),
    Flashcard(
      hanzi: '保重',
      pinyin: 'bǎozhòng',
      meaning: 'cuidarse',
      audioFilePath: 'sounds/保重.mp3',
    ),
  ];

  for (var flashcard in flashcards) {
    await downloadAudio(flashcard);
    await Future.delayed(Duration(
        seconds:
            5)); // Espera 5 segundos entre cada solicitud para evitar errores 429
  }
}

Future<void> downloadAudio(Flashcard flashcard) async {
  try {
    final file = File('${Directory.current.path}/${flashcard.audioFilePath}');
    if (await file.exists()) {
      print('Audio for ${flashcard.hanzi} already exists at ${file.path}');
      return;
    }

    final response = await http.post(
      Uri.parse('http://localhost:5000/synthesize'),
      headers: {
        'Content-Type': 'application/json',
      },
      body: jsonEncode({'text': flashcard.hanzi}),
    );

    if (response.statusCode == 200) {
      final bytes = response.bodyBytes;
      await file.writeAsBytes(bytes);

      print('Audio for ${flashcard.hanzi} saved to ${file.path}');
    } else {
      print(
          'Failed to download audio for ${flashcard.hanzi}: ${response.statusCode}');
    }
  } catch (e) {
    print('Error downloading audio for ${flashcard.hanzi}: $e');
  }
}
